# Form implementation generated from reading ui file 'error_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorDialog(object):
    def setupUi(self, ErrorDialog):
        ErrorDialog.setObjectName("ErrorDialog")
        ErrorDialog.resize(519, 316)
        self.gridLayout = QtWidgets.QGridLayout(ErrorDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gitHubButton = QtWidgets.QPushButton(parent=ErrorDialog)
        self.gitHubButton.setObjectName("gitHubButton")
        self.gridLayout.addWidget(self.gitHubButton, 2, 1, 1, 1)
        self.copyButton = QtWidgets.QPushButton(parent=ErrorDialog)
        self.copyButton.setObjectName("copyButton")
        self.gridLayout.addWidget(self.copyButton, 2, 0, 1, 1)
        self.errorMessageText = QtWidgets.QPlainTextEdit(parent=ErrorDialog)
        self.errorMessageText.setObjectName("errorMessageText")
        self.gridLayout.addWidget(self.errorMessageText, 0, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ErrorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 2, 1, 1)

        self.retranslateUi(ErrorDialog)
        self.buttonBox.accepted.connect(ErrorDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ErrorDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ErrorDialog)

    def retranslateUi(self, ErrorDialog):
        _translate = QtCore.QCoreApplication.translate
        ErrorDialog.setWindowTitle(_translate("ErrorDialog", "Error ⚠"))
        self.gitHubButton.setText(_translate("ErrorDialog", "GitHub Issues Forum"))
        self.copyButton.setText(_translate("ErrorDialog", "Copy to Clipboard"))
